stages:
  - mavenbuild
  - maventest
  - androidbuild
  - androidtest

maven-build:
  stage: mavenbuild
  tags:
    - spring_tag
  script:
    - cd  "Experiments/Lee Vincent Zi Hong"
    - mvn package -B
  
maven-test:
  stage: maventest
  tags:
    - spring_tag
  script:
    - cd "Experiments/Lee Vincent Zi Hong"
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar

android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend
    - ./gradlew build
  artifacts:
    paths:
    - Android_test/app/build/outputs/

android-test:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend
    - ./gradlew test

