stages:
  - mavenbuild
  - maventest
  - mavenDeploy
  - androidbuild
  - androidtest


maven-build:
  stage: mavenbuild
  tags:
    - spring_tag
  script:
    - cd  Backend/userdb/springboot_example/scr
    - mvn package -B
  

maven-test:
  stage: maventest
  tags:
    - spring_tag
  script:
    - cd Backend/userdb/springboot_example
    - mvn test
  artifacts:
    paths:
      - Backend/userdb/springboot_example/target/*.jar

autoDeploy:
  stage: mavenDeploy  #do make a stage with same name!
  tags:
   - spring_tag
  script:
    - cd Backend/userdb/springboot_example
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo

android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/GetFueled/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend/GetFueled/app
    - ./gradlew build
  artifacts:
    paths:
    - app/build/outputs/


android-test:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/GetFueled/gradlew
  tags:
   - android_tag
  script:
    - cd Frontend/GetFueled
    - ./gradlew test


